### PR TITLE
Created table

### PR DESCRIPTION
**Pull request by Ksathwik03**
Issue: 26

#### Short description of what this resolves:
Creating tables for leaderboard

#### Changes proposed in this pull request and/or Screenshots(if applicable):
Screenshot (36)

-
-
-

### CODE REVIEW

**Comment by infern018** [comment]
Nice work, can you make the background a bit light colored, like you mentioned in your issue, this one is not looking elegant

**Comment by infern018** [comment]
pls attach update screenshots

**Comment by Ksathwik03** [comment]
Sir i dont know why but leader board is not working even in the repositry site the is being fetched but displayed

**Comment by infern018** [comment]
Its because the API has changed, you can modify the addToTable function as `addToTable(data.data);` to check changes in your local, make sure to change it back to just `addToTable(data);` after testing

**Comment by Ksathwik03** [comment]
Done sir

**Comment by infern018** [comment]
ss?

**Comment by infern018** [comment]
> Issue: 26
> 
> #### Short description of what this resolves:
> Creating tables for leaderboard
> 
> #### Changes proposed in this pull request and/or Screenshots(if applicable):
> Screenshot (36)

btw why is 2nd row green?

**Comment by Ksathwik03** [comment]
> > Issue: 26
> > #### Short description of what this resolves:
> > Creating tables for leaderboard
> > #### Changes proposed in this pull request and/or Screenshots(if applicable):
> > Screenshot (36)
> 
> btw why is 2nd row green?

My mouse isnt visible in the screen shot sir i hovered my mouse to that row so that easy navigation

**Comment by infern018** [comment]
Can you do one thing, don't change the background color on hover, just the table layout is fine, what you can do is, add some other hover effect, like the row appears a bit bigger or something,

Is that doable?

**Comment by Ksathwik03** [comment]
https://user-images.githubusercontent.com/76401429/135975076-51e73fd2-b413-45fd-bb24-a843c33bfeb7.mp4

**Comment by Ksathwik03** [comment]
> Can you do one thing, don't change the background color on hover, just the table layout is fine, what you can do is, add some other hover effect, like the row appears a bit bigger or something,
> 
> Is that doable?

Sure sir if possible can you increase the points of this issue sir thank you.

**Comment by infern018** [comment]
Thanks @Ksathwik03 , no need for further changes, merging this one, great job !!!

**Comment by Ksathwik03** [comment]
> Thanks @Ksathwik03 , no need for further changes, merging this one, great job !!!

Thanks sir 🥳

**Pull request merged**
