### PR TITLE
Added favicon and did some linting

### PR DESCRIPTION
**Pull request by shlesh**
Issue: 27

Added favicon and did some linting
(even though the index.html file apprears heavily changed, none of the functionality is broken)
image
image

### CODE REVIEW

**Comment by infern018** [comment]
Nice work @shlesh , but few points here:
 - issue #28 was not assigned to you, hence you should not be making a PR unless assigned (although you claimed that first, but its not a good practice)
  - make separate PRs for separate issues, otherwise you won't get points for both issue.
  
 So, delete your second commit in this PR and make a separate PR for it, (keep only favicon changes in this one)

**Comment by shlesh** [comment]
> 
> 
> Nice work @shlesh , but few points here:
> 
>     * issue [Change background of top 3 contributors #28](https://github.com/opencodeiiita/Leaderboard-Frontend/issues/28) was not assigned to you, hence you should not be making a PR unless assigned (although you claimed that first, but its not a good practice)
> 
>     * make separate PRs for separate issues, otherwise you won't get points for both issue.
> 
> 
> So, delete your second commit in this PR and make a separate PR for it, (keep only favicon changes in this one)

Right sir, Iam so sorry i got a bit carried away, will not happen again.
And thank you for taking the time t point it out sir, means a lot!
Now ive removed the bg commit and shall make a new PR for it.

**Comment by infern018** [comment]
Can you delete the commented code and add in your next PR, we should not be sustaining commented code in a PR

**Comment by shlesh** [comment]
@infern018 sorry again sir
done now🥺

**Comment by infern018** [comment]
Great work, and thanks for the linting, much needed :)

**Comment by shlesh** [comment]
Thank you soo much sir, learnt a lot from this too🥺

**Pull request merged**
