### PR TITLE
Added BG colors for the top three Contributors

### PR DESCRIPTION
**Pull request by shlesh**
Issue: 28

Added BG colors for the top three Contributors
Used switch case to try and keep things efficient

image

### CODE REVIEW

**Comment by shlesh** [comment]
@infern018 sir see a "potential" bug in my code,
the coloring is happening according to the order from top, should i make it rank wise?
image
as you can see in the pic 2 people have acieve the same rank, yet only 1 get the color...
does this need to be fixed?

**Comment by infern018** [comment]
Yes indeed, I mentioned in the issue too, if 3 people have same 1st position then they all should be having a GOLDEN background

**Comment by shlesh** [comment]
RIght sir, sorry again :(
image
fixed and pushed

**Comment by infern018** [comment]
Great work @shlesh , thanks...!!!

**Pull request merged**
