### PR TITLE
Centre aligned the content and added header with logo

### PR DESCRIPTION
**Pull request by kaneki-ken260**
Issue: 8 

The content of the webpage has been centrally aligned and a header with a random logo has been added.

### CODE REVIEW

**Comment by infern018** [comment]
Great work @kaneki-ken260 , but change the PR as per the template (no need of hashtags in issue)

**Comment by kaneki-ken260** [comment]
Ok sure!!
Anything else needs to be changed in the PR???

**Comment by infern018** [comment]
Nope, just change it the way as mentioned in the template

**Comment by kaneki-ken260** [comment]
Is it fine now?

**Pull request merged**
